version: '3.8'
services:
  mail:
    image: ixdotai/smtp
    environment:
      - SMARTHOST_ADDRESS=${SMARTHOST_ADDRESS}
      - SMARTHOST_PORT=${SMARTHOST_PORT}
      - SMARTHOST_USER=${SMARTHOST_USER}
      - SMARTHOST_PASSWORD=${SMARTHOST_PASSWORD}
      - SMARTHOST_ALIASES=${SMARTHOST_ALIASES}

  redis:
    image: redis:7.2
    command: "--requirepass '${REDIS_PASSWORD:-redispassword}'"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-redispassword}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    ports:
      - "6379:6379"

  db:
    image: mariadb:10.11
    restart: always
    environment:
      - MYSQL_USER=${MYSQL_USER:-misp}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-example}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-misp}
    command:
      - --innodb-buffer-pool-size=${INNODB_BUFFER_POOL_SIZE:-2048M}
      - --innodb-change-buffering=${INNODB_CHANGE_BUFFERING:-none}
      - --innodb-io-capacity=${INNODB_IO_CAPACITY:-1000}
      - --innodb-log-file-size=${INNODB_LOG_FILE_SIZE:-600M}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"

  misp-core:
    image: ghcr.io/misp/misp-docker/misp-core:${CORE_RUNNING_TAG:-latest}
    build:
      context: core/.
      args:
        CORE_TAG: ${CORE_TAG}
        PHP_VER: ${PHP_VER}
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
      misp-modules:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./configs/:/var/www/MISP/app/Config/
      - ./logs/:/var/www/MISP/app/tmp/logs/
      - ./files/:/var/www/MISP/app/files/
      - ./ssl/:/etc/nginx/certs/
      - ./gnupg/:/var/www/MISP/.gnupg/

  misp-modules:
    image: ghcr.io/misp/misp-docker/misp-modules:${MODULES_RUNNING_TAG:-latest}
    build:
      context: modules/.
      args:
        MODULES_TAG: ${MODULES_TAG}
    environment:
      - REDIS_BACKEND=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PW=${REDIS_PASSWORD:-redispassword}
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "bash", "-c", "</dev/tcp/localhost/6666"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  mysql_data:
